tabs:
  - Server
  - Expert

frames:
  - name: ServerFrame
    tab:  Server
    row:  1
    title: Server Settings

  - name: ButtonFrame
    tab:  Server
    row:  2
    title: Actions
    
  - name: ExpertSettings
    tab:  Expert
    row:  2
    title: Expert Settings
    

inputwidgets:
  - name:  username
    label: User Name
    frame:   ServerFrame
    inputtype: str
    defaultval: USER
    entryopt:
      width:    25
      
  - name:  servername
    label: Server Name
    frame:   ServerFrame
    inputtype: str
    defaultval: ""
    entryopt:
      width:    25

  - name:  password
    label: Password
    frame:   ServerFrame
    inputtype: str
    defaultval: ""
    entryopt:
      width:    25
      show:   "*"

  - name:  remoteportnum
    label: Remote Port Number
    frame:   ServerFrame
    inputtype: int
    defaultval: 8080

  - name:  localportnum
    label: Local Port Number
    frame:   ServerFrame
    inputtype: int
    defaultval: 8080
    
  - name:  usejupyterlab
    label: Use Jupyter Lab
    frame:   ServerFrame
    inputtype: bool
    defaultval: False

  - name:  editexpertsettings
    label: Edit expert settings
    tab:   Expert
    inputtype: bool
    row: 1
    defaultval: False
    visible: False
    ctrlelem:
      - frame:      ExpertSettings
        activewhen: ['', 1]

  - name:  launchservercmd
    label: Start nb server cmd
    frame:   ExpertSettings
    inputtype: str
    defaultval: "tmux new -d -s jupyternb 'jupyter {NBLAB} --no-browser --port={REMOTEPORT}'"
    entryopt:
      width:    40

  - name:  launchlabcmd
    label: Start lab server cmd
    frame:   ExpertSettings
    inputtype: str
    defaultval: "jupyter {NBLAB} --no-browser --port={REMOTEPORT}"
    entryopt:
      width:    40
      
  - name:  listsessionscmd
    label: List sessions cmd
    frame:   ExpertSettings
    inputtype: str
    defaultval: "jupyter notebook list"
    entryopt:
      width:    40

  - name:  stopsessionscmd
    label: Stop sessions cmd
    frame:   ExpertSettings
    inputtype: str
    defaultval: "jupyter {NBLAB} stop {REMOTEPORT}; tmux kill-session -t 0"
    entryopt:
      width:    40
      
  # - name:  sshforwardopt
  #   label: ssh forward opts
  #   frame:   ExpertSettings
  #   inputtype: str
  #   defaultval: "-N -f -L localhost:{LOCALPORT}:localhost:{REMOTEPORT}"
  #   entryopt:
  #     width:    40      
      
buttons:
  - name: startserver
    text: Start Jupyter Server
    frame:  ButtonFrame
    command: self.launchserver

  - name: listservers
    text: List servers
    frame:  ButtonFrame
    command: self.listserver

  - name: shutdownserver
    text: Stop Jupyter Server
    frame:  ButtonFrame
    command: self.stopserver

  - name: startclient
    text: Connect to Server
    frame:  ButtonFrame
    command: self.startconnect

  - name: stopclient
    text: Stop connections
    frame:  ButtonFrame
    command: self.stopconnect

  - name: editexpertbutton
    text: Edit expert settings
    tab: Expert
    row: 0
    command: self.editExpertButton
    
# popupwindow:

# listboxpopupwindows:

# setlistboxfromdict:
      
# setfromdict:

# Add in any additional yaml files with includes section.
# ------------
#includes:
#  - include1.yaml
